// <auto-generated />
using System;
using Data_Access.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_Access.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260226150143_Edit refereshTOken Table")]
    partial class EditrefereshTOkenTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Models.Heater", b =>
                {
                    b.Property<int>("HeaterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeaterId"));

                    b.Property<string>("HeaterType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<int>("PowerValue")
                        .HasColumnType("int");

                    b.HasKey("HeaterId");

                    b.HasIndex("HouseId");

                    b.ToTable("heaters");
                });

            modelBuilder.Entity("Models.Models.House", b =>
                {
                    b.Property<int>("HouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HouseId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("HouseId");

                    b.HasIndex("OwnerId");

                    b.ToTable("houses");
                });

            modelBuilder.Entity("Models.Models.MonthlyCostReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<double>("MedianHeaterValue")
                        .HasColumnType("float");

                    b.Property<decimal>("MonthlyAverageCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReportMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalWorkingHours")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("HouseId");

                    b.ToTable("monthlyCostReports");
                });

            modelBuilder.Entity("Models.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OwnerId");

                    b.ToTable("owners");
                });

            modelBuilder.Entity("Models.Models.SensorReading", b =>
                {
                    b.Property<int>("SensorReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorReadingId"));

                    b.Property<int>("HeaterId")
                        .HasColumnType("int");

                    b.Property<double>("HeaterValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReadingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkingHours")
                        .HasColumnType("int");

                    b.HasKey("SensorReadingId");

                    b.HasIndex("HeaterId");

                    b.ToTable("sensorReadings");
                });

            modelBuilder.Entity("Models.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ownerId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("ownerId")
                        .IsUnique()
                        .HasFilter("[ownerId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.Models.Heater", b =>
                {
                    b.HasOne("Models.Models.House", "house")
                        .WithMany("heaters")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("house");
                });

            modelBuilder.Entity("Models.Models.House", b =>
                {
                    b.HasOne("Models.Models.Owner", "owner")
                        .WithMany("houses")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("Models.Models.MonthlyCostReport", b =>
                {
                    b.HasOne("Models.Models.House", "house")
                        .WithMany()
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("house");
                });

            modelBuilder.Entity("Models.Models.SensorReading", b =>
                {
                    b.HasOne("Models.Models.Heater", "heater")
                        .WithMany()
                        .HasForeignKey("HeaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("heater");
                });

            modelBuilder.Entity("Models.Models.User", b =>
                {
                    b.HasOne("Models.Models.Owner", "owner")
                        .WithOne("user")
                        .HasForeignKey("Models.Models.User", "ownerId");

                    b.OwnsMany("Models.Models.RefereshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("exbireon")
                                .HasColumnType("datetime2");

                            b1.Property<string>("refereshToken")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("RefereshToken");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshTokens");

                    b.Navigation("owner");
                });

            modelBuilder.Entity("Models.Models.House", b =>
                {
                    b.Navigation("heaters");
                });

            modelBuilder.Entity("Models.Models.Owner", b =>
                {
                    b.Navigation("houses");

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
